### PR TITLE
Add OCR configuration to include/exclude terms from base list

### PR DESCRIPTION
**Pull request by cccs-rs**

### CODE REVIEW

**Review by gdesmar — APPROVED** [review]

**Comment by cccs-kevin** [comment]
> > How do we document this so that service writes / consumers are aware of it?
> 
> So far documentation will be added to the services using OCR, but we can also add this to the official docs... just don't know where exactly.

Does somewhere here make sense?
image

**Comment by cccs-rs** [comment]
> > > How do we document this so that service writes / consumers are aware of it?
> > 
> > 
> > So far documentation will be added to the services using OCR, but we can also add this to the official docs... just don't know where exactly.
> 
> Does somewhere here make sense? image

Not really as it's not really developer-focused, it's more for administrators of the system.

Maybe under Administration → Service Management?

**Comment by gdesmar** [comment]
I think it may be more of a Installation -> Configuration topic, to tell system administrators how to personalized their instance? For now, since the configuration is done in the service, having the documentation in the service's repo looks good to me.

**Comment by cccs-kevin** [comment]
Sounds good! Let's add it to Administration → Service Management and call it documentation-wise

**Pull request merged**
